#!/usr/bin/env python3
"""
bake_state.py — Endale local state baker
=========================================

Reads endale-state.json (exported from the app via the "Export State" button
in the sidebar footer) and writes data/state/local-state.js, which seeds
localStorage when the app loads on GitHub Pages.

Usage
-----
  python bake_state.py                     # reads endale-state.json
  python bake_state.py my-export.json      # reads a named file

Workflow
--------
  1. Open the app locally (file:// or localhost).
  2. Make all your changes — nav edits, custom cards, image links, maps, etc.
  3. Click "Export State" in the sidebar footer  → saves endale-state.json.
  4. Move endale-state.json to the repo root (same folder as this script).
  5. Run:  python bake_state.py
  6. Commit and push.  GitHub Pages now loads with all your changes baked in.

What gets baked
---------------
  endale-nav           Navigation tree (groups, page order)
  endale-custom-cards  Cards created through the app UI
  endale-additions     Cards added to existing wiki pages
  endale-hidden        Cards / groups hidden from pages
  endale-overrides     Field edits made to existing wiki cards
  endale-maps          Map builder maps and floors
  endale-board         Session board (Active Manager) pin layout

Keys absent from the export file are silently skipped — existing baked values
for those keys are cleared (an empty STATE means "no seed data for this key").
"""

import json
import os
import sys
from datetime import datetime

# ---------------------------------------------------------------------------
# Config
# ---------------------------------------------------------------------------

KEYS_TO_BAKE = [
    'endale-nav',
    'endale-custom-cards',
    'endale-additions',
    'endale-hidden',
    'endale-overrides',
    'endale-maps',
    'endale-board',
]

OUTPUT_PATH  = os.path.join('data', 'state', 'local-state.js')
INDEX_PATH   = 'index.html'
SCRIPT_TAG   = '<script src="data/state/local-state.js"></script>'
INSERT_BEFORE = '<!-- ── App ── -->'

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def load_export(path):
    if not os.path.exists(path):
        print(f'Error: "{path}" not found.')
        print()
        print('Steps to export:')
        print('  1. Open the app in your browser (local file or localhost).')
        print('  2. Click "Export State" in the sidebar footer.')
        print('  3. Move the downloaded endale-state.json to this folder.')
        print('  4. Re-run:  python bake_state.py')
        sys.exit(1)

    with open(path, 'r', encoding='utf-8') as f:
        try:
            return json.load(f)
        except json.JSONDecodeError as e:
            print(f'Error: could not parse {path}: {e}')
            sys.exit(1)


def build_js(state, timestamp):
    state_json = json.dumps(state, indent=2, ensure_ascii=False)
    # Indent the STATE value by two extra spaces to sit inside the IIFE
    state_indented = '\n'.join(
        '  ' + line for line in state_json.splitlines()
    )
    return (
        '/* ═══════════════════════════════════════════════\n'
        '   ENDALE — Baked local state\n'
        f'   Generated by bake_state.py on {timestamp}\n'
        '   Do not edit manually — re-run bake_state.py to regenerate.\n'
        '   ═══════════════════════════════════════════════ */\n'
        '\n'
        '(function () {\n'
        '  var STATE =\n'
        f'{state_indented};\n'
        '\n'
        '  for (var k in STATE) {\n'
        '    if (Object.prototype.hasOwnProperty.call(STATE, k)) {\n'
        '      localStorage.setItem(k, JSON.stringify(STATE[k]));\n'
        '    }\n'
        '  }\n'
        '})();\n'
    )


def ensure_script_tag():
    """Add the local-state.js script tag to index.html if it's missing."""
    if not os.path.exists(INDEX_PATH):
        print(f'  ! {INDEX_PATH} not found — skipping script tag check.')
        return

    with open(INDEX_PATH, 'r', encoding='utf-8') as f:
        html = f.read()

    if SCRIPT_TAG in html:
        return  # already present

    if INSERT_BEFORE in html:
        html = html.replace(
            INSERT_BEFORE,
            f'<!-- \u2500\u2500 Baked state (generated by bake_state.py) \u2500\u2500 -->\n'
            f'{SCRIPT_TAG}\n\n'
            f'{INSERT_BEFORE}'
        )
        with open(INDEX_PATH, 'w', encoding='utf-8') as f:
            f.write(html)
        print(f'  \u2713 Added script tag to {INDEX_PATH}')
    else:
        print(f'  ! Could not auto-insert script tag into {INDEX_PATH}.')
        print(f'    Add this line before the app scripts:')
        print(f'    {SCRIPT_TAG}')


def summarise(state):
    for k in KEYS_TO_BAKE:
        if k not in state:
            print(f'  (skipped)  {k}')
            continue
        v = state[k]
        if isinstance(v, list):
            print(f'  {len(v):>4} item(s)  {k}')
        elif isinstance(v, dict):
            print(f'  {len(v):>4} key(s)   {k}')
        else:
            print(f'             {k}')


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main():
    input_file = sys.argv[1] if len(sys.argv) > 1 else 'endale-state.json'
    raw        = load_export(input_file)

    # Keep only the keys we care about
    state     = {k: raw[k] for k in KEYS_TO_BAKE if k in raw}
    timestamp = datetime.now().strftime('%Y-%m-%d %H:%M')

    # Write output
    os.makedirs(os.path.dirname(OUTPUT_PATH), exist_ok=True)
    js = build_js(state, timestamp)
    with open(OUTPUT_PATH, 'w', encoding='utf-8') as f:
        f.write(js)

    # Report
    print(f'Baked {len(state)}/{len(KEYS_TO_BAKE)} keys  →  {OUTPUT_PATH}')
    summarise(state)
    print()

    # Make sure index.html loads the file
    ensure_script_tag()

    print()
    print('Done. Commit data/state/local-state.js and push.')


if __name__ == '__main__':
    main()
