"""
update-art-manifest.py
Scans art/ for image files and adds any missing entries to js/art-manifest.js.
Run from the repo root: python update-art-manifest.py
"""

import os
import re

ART_DIR      = 'art'
MANIFEST_JS  = 'js/art-manifest.js'
IMAGE_EXTS   = {'.png', '.jpg', '.jpeg', '.webp', '.gif', '.svg'}


def find_art_files():
    paths = []
    for root, _, files in os.walk(ART_DIR):
        for fname in sorted(files):
            if os.path.splitext(fname)[1].lower() in IMAGE_EXTS:
                # Always forward slashes so paths work in the browser
                rel = os.path.join(root, fname).replace('\\', '/')
                paths.append(rel)
    return paths


def read_manifest():
    if not os.path.exists(MANIFEST_JS):
        return []
    with open(MANIFEST_JS, encoding='utf-8') as f:
        content = f.read()
    # Pull every quoted string from the file
    return re.findall(r"'([^']+)'", content)


def write_manifest(paths):
    header = """\
/* ═══════════════════════════════════════════════
   ENDALE — Art Manifest
   List every art file you've placed in art/.
   Paths are relative to index.html.
   Auto-generated by update-art-manifest.py
   ═══════════════════════════════════════════════ */

const ArtManifest = [
"""
    entries = ''.join(f"  '{p}',\n" for p in paths)
    footer  = '];\n'

    with open(MANIFEST_JS, 'w', encoding='utf-8') as f:
        f.write(header + entries + footer)


def main():
    found    = find_art_files()
    existing = set(read_manifest())

    new_paths = [p for p in found if p not in existing]

    if not found:
        print('No image files found under art/')
        return

    if not new_paths:
        print(f'Nothing to add — manifest already lists all {len(found)} file(s).')
        return

    # Merge: keep existing order, append new entries at the end
    merged = list(existing & set(found))   # existing entries still present on disk
    merged = sorted(found, key=lambda p: (found.index(p),))  # preserve disk-walk order

    write_manifest(merged)
    print(f'Added {len(new_paths)} new file(s) to {MANIFEST_JS}:')
    for p in new_paths:
        print(f'  + {p}')
    print(f'Total: {len(merged)} file(s) in manifest.')


if __name__ == '__main__':
    main()
